### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by OctoNezd** [OctoNezd/RequestsComposer#1]
- [ ] Highlight JSON/Make a treeview for JSON
- [ ] Ability to save/load requests
- [ ] Set binary request body
- [ ] Support choosing encodings of response/request
